### PR TITLE
remove freeTransform from solve

### LINKED ISSUE #23: Implicitely call `freeTransform` in all functions that modify the problem.
Up to now, we called `SCIPfreeTransform` directly after `SCIPsolve`, but stored (copied) some important results, such as best solution, objective value and status.

We now want to expose more results (such as solving time, see [#18](https://github.com/SCIP-Interfaces/SCIP.jl/pull/18) in SCIP.jl) and this approach is no longer viable.

First, we should remove the call to `SCIPfreeTransform` in the solve, but introduce it in all modifying methods.

Then (optionally) clean up some of the copied results that we no longer need.

### PR DESCRIPTION
**Pull request by fserra**
closes #23

### CODE REVIEW

**Comment by mlubin** [comment]
What happens if you call the querying methods after calling a transformation method?

**Comment by fserra** [comment]
some information is lost. For instance, the solving time, which is going to return 0

**Comment by mlubin** [comment]
Is it worth keeping a status flag and returning errors in that case?

**Comment by fserra** [comment]
could be...

Also we should probably start checking return values in SCIP.jl

**Comment by fserra** [comment]
so from JuMP, user can only call these `cb*` methods during solving, right? If that is the case, then I guess it is pretty simple to do the checking

**Comment by mlubin** [comment]
The cb methods are only supposed to be called from inside a callback.

**Comment by fserra** [comment]
yes, and from inside a callback is the only place where you can interact with the solving process, right?

**Comment by mlubin** [comment]
Yes

**Comment by fserra** [comment]
Ok. Anyway, it might not make sense to have this stage flag in CSIP. If we are going to implement some function calling SCIP directly from SCIP.jl (getsolvetime), then we might want to have this flag on SCIP.jl

what do you think?

**Comment by mlubin** [comment]
That's okay as well. Maybe add some documentation on the CSIP side to let other users know when it's correct to call the different methods?

**Comment by fserra** [comment]
Ok. The idea would be to refer the users to the documentation of SCIP,
since this stage business is explained there

**Comment by leethargo** [comment]
I don't understand really. If we decide to call `freeTransform` implicitely where needed, the users of CSIP don't need to know about SCIP stages necessarily.

The other part about the `cb*` methods is not derived from SCIP, so there's no documentation to point to.

**Comment by fserra** [comment]
We don't care about cb methods, they can always be called inside callbacks
(because the stage is always Solving)

For the other methods, sure, we could forget completely about SCIP, or let
users understand that SCIP has stages and a problem can be modified on a
given stage and on this stage some information is just not available.

**Comment by leethargo** [comment]
I see that there are lots of changes in addition to just calling `freeTransform`. Are these about removing the copied results?

**Comment by fserra** [comment]
yes and updating the objective

**Comment by leethargo** [comment]
I'm running the tests with SCIP.jl, too, then we can merge it.

**Pull request merged**
